// <auto-generated />
namespace CodeFirst_Sqlite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class AddView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddView));
        
        string IMigrationMetadata.Id
        {
            get { return "201905160305294_AddView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
